const proyectos = [
    {
    id: 17,
    titulo: "Programas para calculadora HP-PRIME",
    descripcion:
      "Colección de programas desarrollados para la calculadora gráfica HP-PRIME. Los programas están escritos en el lenguaje de programación nativo de la HP-PRIME y están disponibles como proyectos open source en GitHub.",
    imagen: "img/programas-hp/portada.jpg",
    enlace: "programas-hp-prime.html",
    etiquetas: [
      "Programación",
      "Calculadora",
      "HP-PRIME",
      "Matemáticas",
      "Ingeniería Civil",
    ],
    mencion: "programacion",
    fecha: "2019-09-21",
    logros: [
      "Desarrollo de programas para la calculadora HP-PRIME en lenguaje PPL",
      "Programción de algoritmos de métodos numéricos y funciones matemáticas",
      "Herramientas automatizadas para estudiantes de ingeniería civil y matemáticas",
    ],
    software_usado: "PPL, HP-PRIME",
    impacto:
      "Facilita el aprendizaje y la aplicación de conceptos matemáticos e ingenieriles mediante programas personalizados para la HP-PRIME.",
    galeria: ["seccion_viga.png", "verificaciones.png"],
  },
  {
    id: 16,
    titulo: "Diseño a Flexión de Vigas de Hormigón Armado ACI 318-19 (Python)",
    descripcion:
      "Herramienta computacional interactiva en Python para el cálculo del refuerzo longitudinal a flexión en vigas rectangulares. Implementa verificaciones automáticas de acero mínimo, máximo y ductilidad según la norma ACI 318-19/2025, generando diagramas técnicos y reportes de diseño.",
    imagen: "img/proyectos/0-programacion/diseno-a-flexion.jpg",
    enlace: "https://github.com/cing1/Diseno-a-flexion-de-vigas-de-HA-ACI318",
    etiquetas: [
      "Python",
      "Ingeniería Estructural",
      "ACI 318"
    ],
    mencion: "programacion",
    fecha: "2026-04-21",
    logros: [
      "Implementación de 3 métodos equivalentes para el cálculo de A_s",
      "Verificación automática de normativas ACI 318 (límites de acero y condición de falla dúctil)",
      "Generación de visualizaciones técnicas de secciones, diagramas de deformación y gráficos comparativos de rangos permitidos"
    ],
    software_usado: "Python, Jupyter Notebook, NumPy, Matplotlib, SciPy",
    impacto:
      "Automatiza y optimiza el proceso de diseño estructural, reduciendo errores de cálculo manual, garantizando el cumplimiento normativo.",
    galeria: ["seccion_viga.png", "verificaciones.png"],
  },
  {
    id: 15,
    titulo: "Biblioteca de Ingeniería Civil",
    descripcion:
      "Plataforma web para la visualización y descarga de libros, solucionarios y apuntes de libre acceso para estudiantes y profesionales de Ingeniería Civil. Funciona como una biblioteca digital centralizada que facilita el acceso rápido a material académico, con recursos alojados en Google Drive y cargados dinámicamente en la interfaz web.",
    imagen: "img/proyectos/0-programacion/biblioteca-ing-civil.jpg",
    enlace: "https://github.com/cing1/biblioteca-ingenieria-civil",
    etiquetas: [
      "Web",
      "HTML5",
      "CSS3",
      "JavaScript",
      "Google Drive API",
      "Hosting estático",
    ],
    mencion: "programacion",
    fecha: "2025-08-12",
    logros: [
      "Integración exitosa con Google Drive para carga automática y sincronizada",
      "Interfaz ligera y compatible con múltiples dispositivos",
      "Acceso libre y gratuito para la comunidad universitaria",
    ],
    software_usado: "HTML5, CSS3, JavaScript, Google Drive API",
    impacto:
      "Facilita el acceso a material académico de Ingeniería Civil sin costos adicionales, beneficiando a estudiantes y profesionales de la USFX y la comunidad en general.",
    galeria: [""],
  },
  {
    id: 14,
    titulo: "Sitio web Sociedad Científica SCEIC-USFX",
    descripcion:
      "Desarrollo y gestión del sitio web oficial de la Sociedad Científica de Estudiantes de Ingeniería Civil (SCEIC-USFX), con información institucional, eventos, publicaciones y recursos para estudiantes. Proyecto open source disponible en GitHub.",
    imagen: "img/proyectos/0-programacion/pagina-sceic.jpg",
    enlace: "https://github.com/cing1/Sociedad-Cient-fica-SCEIC-USFX",
    etiquetas: [
      "Web",
      "Sociedad Científica",
      "Ingeniería Civil",
      "Gestión Académica",
      "Open Source",
      "Programación",
    ],
    mencion: "programacion",
    fecha: "2026-04-04",
    logros: [
      "Desarrollo y mantenimiento del sitio web institucional",
      "Difusión de eventos y publicaciones científicas",
      "Implementación de recursos y enlaces útiles para estudiantes",
      "Código abierto y documentado en GitHub",
    ],
    software_usado: "HTML, CSS, JavaScript, Google Drive API",
    impacto:
      "Fortalece la comunicación y el acceso a recursos académicos para estudiantes de ingeniería civil.",
    galeria: ["../img/proyectos/0-programacion/pagina-sceic.jpg"],
  },
  {
    id: 13,
    titulo: "Diagrama de interacción de columnas (Python)",
    descripcion:
      "Aplicación en Python para el cálculo y visualización del diagrama de interacción de columnas de concreto armado, permitiendo analizar la capacidad axial y de momento según parámetros geométricos y de materiales. Proyecto open source disponible en GitHub.",
    imagen: "img/proyectos/0-programacion/diagrama-de-interaccion.jpg",
    enlace: "https://github.com/cing1/Diagrama-de-interaccion-de-columnas",
    etiquetas: [
      "Python",
      "Columnas",
      "Concreto Armado",
      "Diagrama de Interacción",
      "Diseño Estructural",
      "Open Source",
      "Programación",
    ],
    mencion: "programacion",
    fecha: "2026-04-11",
    logros: [
      "Desarrollo de herramienta para análisis de columnas de concreto armado",
      "Cálculo y graficación del diagrama de interacción axial-momento",
      "Interfaz gráfica para ingreso de parámetros y visualización de resultados",
      "Código abierto y documentado en GitHub",
    ],
    software_usado: "Python, Tkinter, Matplotlib, NumPy",
    impacto:
      "Facilita el análisis y diseño de columnas de concreto armado mediante software libre.",
    galeria: ["img/proyectos/0-programacion/diagrama-interaccion.jpg"],
  },
  {
    id: 12,
    titulo: "Diseño de pavimento flexible AASHTO 93 (Python)",
    descripcion:
      "Aplicación en Python para el diseño de pavimentos flexibles según la metodología AASHTO 1993. Permite calcular el espesor de las capas estructurales considerando parámetros de tránsito, clima y materiales. Proyecto open source disponible en GitHub.",
    imagen: "img/proyectos/0-programacion/diseno-pavimento-aashto93.jpg",
    enlace: "https://github.com/cing1/diseno-de-pavimento-flexible-aashto93",
    etiquetas: [
      "Python",
      "Pavimentos",
      "AASHTO 93",
      "Diseño Vial",
      "Ingeniería Civil",
      "Open Source",
      "Programación",
    ],
    mencion: "programacion",
    fecha: "2026-04-20",
    logros: [
      "Desarrollo de herramienta para diseño de pavimentos flexibles",
      "Implementación de la metodología AASHTO 1993 en Python",
      "Interfaz gráfica para ingreso de parámetros y visualización de resultados",
      "Código abierto y documentado en GitHub",
    ],
    software_usado: "Python, Tkinter, NumPy",
    impacto:
      "Facilita el diseño académico y profesional de pavimentos flexibles mediante software libre.",
    galeria: ["../img/proyectos/0-programacion/diseno-pavimento-aashto93.jpg"],
  },
  {
    id: 11,
    titulo: "Análisis de vigas continuas por rigidez (Python)",
    descripcion:
      "Aplicación en Python para el análisis estructural de vigas continuas mediante el método de rigidez, permitiendo calcular desplazamientos y diagramas de momentos y cortantes. Proyecto open source disponible en GitHub.",
    imagen: "img/proyectos/0-programacion/fem-vigas-continuas.jpg",
    enlace: "https://github.com/cing1/Analisis-vigas-continuas-rigidez",
    etiquetas: [
      "Python",
      "Estructural",
      "Método de Rigidez",
      "Vigas Continuas",
      "Análisis Estructural",
      "Open Source",
      "Programación",
    ],
    mencion: "programacion",
    fecha: "2026-04-18",
    logros: [
      "Desarrollo de herramienta para análisis de vigas continuas",
      "Implementación del método de rigidez en Python",
      "Visualización de resultados: desplazamientos, momentos y cortantes",
      "Código abierto y documentado en GitHub",
    ],
    software_usado: "Python, Matplotlib, NumPy",
    impacto:
      "Facilita el análisis estructural académico y profesional de vigas continuas mediante software libre.",
    galeria: ["../img/proyectos/0-programacion/fem-vigas-continuas.jpg"],
  },
  {
    id: 10,
    titulo: "Análisis y diseño estructural de edificio",
    descripcion:
      "Análisis y diseño estructural de edificio: modelado de la geometría estructural, definición de sistemas estructurales, aplicación de cargas (sismo, viento, gravedad), análisis de esfuerzos y desplazamientos, dimensionamiento de elementos (columnas, vigas, losas), verificación de normativas (ACI, AISC, NBDS) y elaboración de planos estructurales.",
    imagen: "./img/proyectos/analisis-diseno-estructural-edificio/06.png",
    enlace: "#",
    etiquetas: [
      "Estructural",
      "Concreto Armado",
      "Diseño Estructural",
      "Análisis Estructural",
      "Cargas",
      "Esfuerzos",
      "Desplazamientos",
      "Dimensionamiento",
      "Verificación de normativas",
      "Elaboración de planos estructurales",
    ],
    mencion: "estructural",
    fecha: "2026-04-20",
    logros: [
      "Modelado de la geometría estructural del edificio",
      "Definición de sistemas estructurales",
      "Aplicación de cargas (sismo, viento, gravedad)",
      "Análisis de esfuerzos y desplazamientos",
      "Dimensionamiento de elementos (columnas, vigas, losas)",
      "Verificación de normativas (ACI, AISC, NBDS)",
      "Elaboración de planos estructurales",
    ],
    software_usado: "Robot Structural, Revit, AutoCad, Excel, Mathcad",
    impacto: "Optimización del diseño estructural y cumplimiento normativo.",
    galeria: [
      "./img/proyectos/analisis-diseno-estructural-edificio/01.png",
      "./img/proyectos/analisis-diseno-estructural-edificio/02.png",
      "./img/proyectos/analisis-diseno-estructural-edificio/03.png",
      "./img/proyectos/analisis-diseno-estructural-edificio/04.png",
      "./img/proyectos/analisis-diseno-estructural-edificio/05.png",
      "./img/proyectos/analisis-diseno-estructural-edificio/06.png",
      "./img/proyectos/analisis-diseno-estructural-edificio/07.png",
      "./img/proyectos/analisis-diseno-estructural-edificio/08.png",
      
    
    ],
  },
  {
    id: 9,
    titulo: "Modelado BIM de Edificio Multifamiliar",
    descripcion:
      "Modelado BIM integral de un edificio multifamiliar: creación del modelo arquitectónico, estructural e instalaciones hidrosanitarias; coordinación interdisciplinaria (arquitectura, estructura e instalaciones), generación de planos constructivos y tablas de cantidades, y preparación de entregables BIM para obra.",
    imagen: "./img/proyectos/9-modelado_bim_edificio_multifamiliar/portada.jpg",
    enlace: "#",
    etiquetas: [
      "Revit",
      "BIM",
      "Edificio",
      "Concreto Armado",
      "Diseño Estructural",
      "Modelado 3D",
    ],
    mencion: "estructural",
    fecha: "2025-12-10",
    logros: [
      "Modelado BIM arquitectónico, estructural e hidrosanitario",
      "Coordinación interdisciplinaria entre especialidades",
      "Generación de planos constructivos y tablas de cantidades",
      "Preparación de entregables BIM para obra",
    ],
    software_usado: "Revit, Navisworks",
    impacto:
      "Detección temprana de interferencias y generación de entregables de alta calidad para obra.",
    galeria: [
      "./img/proyectos/9-modelado_bim_edificio_multifamiliar/imagen_1.jpg",
      "./img/proyectos/9-modelado_bim_edificio_multifamiliar/imagen_2.jpg",
      "./img/proyectos/9-modelado_bim_edificio_multifamiliar/imagen_3.jpg",
      "./img/proyectos/9-modelado_bim_edificio_multifamiliar/imagen_4.jpg",
      "./img/proyectos/9-modelado_bim_edificio_multifamiliar/imagen_5.jpg",
      "./img/proyectos/9-modelado_bim_edificio_multifamiliar/imagen_6.jpg",
      "./img/proyectos/9-modelado_bim_edificio_multifamiliar/imagen_7.jpg",
    ],
  },
  {
    id: 8,
    titulo: "Diseño Geométrico de Carreteras implementando metodología BIM",
    descripcion:
      "Alineamiento horizontal y vertical, peraltes, secciones transversales y movimiento de tierras.",
    imagen:
      "./img/proyectos/4-diseno_geometrico_de_carreteras_implementando_metodologia_bim/portada.jpg",
    enlace: "#",
    etiquetas: [
      "BIM",
      "Civil 3D",
      "Carreteras",
      "Infraworks",
      "Navisworks",
      "Diseño Vial",
      "Fotogrametría",
      "Cronograma",
      "Infraestructura",
    ],
    mencion: "carreteras",
    fecha: "2025-12-03",
    logros: [
      "Levantamiento fotogramétrico",
      "Procesamiento fotogramétrico",
      "Modelado topográfico",
      "Diseño geométrio 3D",
      "Elaboración de planos",
      "Presupuesto y cronograma de ejecución",
      "Simulación según cronograma de obra",
    ],
    software_usado:
      "Civil 3D, Infraworks, AutoCAD, Navisworks, MS Project, Prescom, Agisoft Metashape, Google Earth Pro, Global Mapper",
    impacto:
      "Diseño más preciso y colaborativo, mejorando la toma de decisiones en etapas tempranas.",
    galeria: [
      "./img/proyectos/4-diseno_geometrico_de_carreteras_implementando_metodologia_bim/imagen_1.jpg",
      "./img/proyectos/4-diseno_geometrico_de_carreteras_implementando_metodologia_bim/imagen_2.jpg",
      "./img/proyectos/4-diseno_geometrico_de_carreteras_implementando_metodologia_bim/imagen_3.jpg",
      "./img/proyectos/4-diseno_geometrico_de_carreteras_implementando_metodologia_bim/imagen_4.jpg",
      "./img/proyectos/4-diseno_geometrico_de_carreteras_implementando_metodologia_bim/imagen_5.jpg",
      "./img/proyectos/4-diseno_geometrico_de_carreteras_implementando_metodologia_bim/imagen_6.jpg",
      "./img/proyectos/4-diseno_geometrico_de_carreteras_implementando_metodologia_bim/imagen_7.jpg",
      "./img/proyectos/4-diseno_geometrico_de_carreteras_implementando_metodologia_bim/imagen_8.jpg",
      "./img/proyectos/4-diseno_geometrico_de_carreteras_implementando_metodologia_bim/imagen_9.jpg",
      "./img/proyectos/4-diseno_geometrico_de_carreteras_implementando_metodologia_bim/imagen_10.jpg",
    ],
  },
  {
    id: 6,
    titulo: "Análisis, Diseño y Modelado BIM de Puente Postensado",
    descripcion:
      "Cálculo estructural según AASHTO, diseño de postensado y modelado BIM completo de puente.",
    imagen: "./img/proyectos/2-analisis_diseño_puente_postensado/portada.jpg",
    enlace: "#",
    etiquetas: [
      "Puentes",
      "Postensado",
      "AASHTO",
      "SAP2000",
      "BIM",
      "Infraestructura",
      "CSI Bridge",
    ],
    mencion: "estructural",
    fecha: "2025-08-01",
    logros: [
      "Análisis y diseño estructural según normativa AASHTO",
      "Diseño de sistema de postensado",
      "Modelado BIM completo del puente",
      "Elaboración de planos constructivos",
    ],
    software_usado: "SAP2000, CSI Bridge, Revit",
    impacto:
      "Garantizar la estabilidad y seguridad de la estructura bajo estándares internacionales.",
    galeria: [
      "https://picsum.photos/1000/600?project=4-img1",
      "https://picsum.photos/1000/600?project=4-img2",
      "https://picsum.photos/1000/600?project=4-img3",
    ],
  },
  {
    id: 5,
    titulo: "Diseño geométrico de carretera, tramo doble vía Sucre-Yamparáez",
    descripcion:
      "Modelado topográfico, alineamientos, perfiles y diseño geométrico completo.",
    imagen: "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/portada.png",
    enlace: "#",
    etiquetas: ["Civil 3D", "Carreteras", "BIM", "Topografía", "Diseño Vial"],
    mencion: "carreteras",
    fecha: "2025-07-10",
    logros: [
      "Levantamiento fotogramétrico",
      "Procesamiento fotogramétrico",
      "Modelado topográfico",
      "Diseño geométrio 3D",
      "Elaboración de planos",
      "Presupuesto y cronograma de ejecución",
      "Simulación según cronograma de obra",
    ],
    software_usado:
      "Civil 3D, Infraworks, AutoCAD, Navisworks, MS Project, Prescom, Agisoft Metashape, Google Earth Pro, Global Mapper",
    impacto:
      "Mejora de la infraestructura vial, reduciendo tiempos de viaje y aumentando la seguridad.",
    galeria: [
      "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/imagen_1.png",
      "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/imagen_2.png",
      "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/imagen_3.png",
      "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/imagen_4.png",
      "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/imagen_5.png",
      "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/imagen_6.png",
      "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/imagen_7.png",
      "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/imagen_8.png",
      "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/imagen_9.png",
      "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/imagen_10.png",
      "./img/proyectos/1-tramo_doble_via_sucre-yamparaez/imagen_11.png",
    ],
  },
  {
    id: 4,
    titulo: "Diseño de red de alcantarillado sanitario urbano",
    descripcion:
      "Proyecto integral que incluye el análisis de caudales, modelación hidráulica, trazo de colectores y elaboración de planos técnicos para la red de alcantarillado sanitario urbano.",
    imagen: "./img/proyectos/6-sistema_de_drenaje_sanitario/portada.jpg",
    enlace: "#",
    etiquetas: [
      "Alcantarillado",
      "Drenaje Sanitario",
      "Hidráulica",
      "Infraestructura Urbana",
      "Civil 3D",
      "Saneamiento",
      "Excel",
    ],
    mencion: "sanitaria",
    fecha: "2024-06-17",
    logros: [
      "Análisis de caudales y parámetros hidrológicos",
      "Modelación hidráulica de la red de colectores",
      "Trazo y diseño de la red sanitaria",
      "Elaboración de planos técnicos y memorias de cálculo",
    ],
    software_usado: "Civil 3D, Excel, WaterCAD",
    impacto:
      "Mejora de las condiciones sanitarias urbanas y adecuado manejo de aguas residuales.",
    galeria: [
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_1.jpg",
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_2.jpg",
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_3.jpg",
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_4.jpg",
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_5.jpg",
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_6.jpg",
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_7.jpg",
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_8.jpg",
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_9.jpg",
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_10.jpg",
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_11.jpg",
      "./img/proyectos/6-sistema_de_drenaje_sanitario/imagen_12.jpg",
    ],
  },
  {
    id: 3,
    titulo: "Diseño y Modelado de Estructura Metálica",
    descripcion:
      "Diseño de conexiones, análisis de cargas y modelado 3D de estructura metálica tipo tinglado.",
    imagen:
      "./img/proyectos/5-diseno_y_modelado_de_estructura_metalica/portada.jpg",
    enlace: "#",
    etiquetas: [
      "Acero",
      "SAP2000",
      "Estructuras Metálicas",
      "AISC",
      "Revit",
      "Robot Structural Analysis",
      "Viento",
      "Conexiones",
    ],
    mencion: "estructural",
    fecha: "2023-10-15",
    logros: [
      "Análisis de cargas gravitacionales y de viento",
      "Diseño de elementos y conexiones metálicas según AISC",
      "Modelado 3D de la estructura tipo tinglado",
      "Elaboración de planos y memoria de cálculo",
    ],
    software_usado: "SAP2000, Revit, Robot Structural Analysis",
    impacto:
      "Estructura segura y eficiente, optimizando la cantidad de acero requerida.",
    galeria: [
      "./img/proyectos/5-diseno_y_modelado_de_estructura_metalica/imagen_1.jpg",
      "./img/proyectos/5-diseno_y_modelado_de_estructura_metalica/imagen_2.jpg",
      "./img/proyectos/5-diseno_y_modelado_de_estructura_metalica/imagen_3.jpg",
      "./img/proyectos/5-diseno_y_modelado_de_estructura_metalica/imagen_4.jpg",
    ],
  },
  {
    id: 2,
    titulo: "Modelado Estructural Bahira Gran Hotel",
    descripcion: "Modelado estructura de edificio de concreto armado.",
    imagen: "./img/proyectos/7-modelado_est_bahria_grand_hotel/portada.jpg",
    enlace: "#",
    etiquetas: [
      "Revit",
      "Concreto Armado",
      "Diseño Estructural",
      "Edificios",
      "Modelado 3D",
      "BIM",
    ],
    mencion: "estructural",
    fecha: "2022-11-20",
    logros: [
      "Modelado BIM estructural detallado del edificio",
      "Coordinación interdisciplinaria de modelos",
      "Generación de planos constructivos y tablas de cantidades",
    ],
    software_usado: "Revit, Tekla Structures",
    impacto:
      "Facilitar la coordinación interdisciplinaria y la estimación precisa de materiales.",
    galeria: [
      "./img/proyectos/7-modelado_est_bahria_grand_hotel/imagen_1.jpg",
      "./img/proyectos/7-modelado_est_bahria_grand_hotel/imagen_2.jpg",
      "./img/proyectos/7-modelado_est_bahria_grand_hotel/imagen_3.jpg",
    ],
  },
  {
    id: 1,
    titulo: "Modelado estructura Stanley Condominium",
    descripcion: "Modelado estructura de edificio de concreto armado",
    imagen: "./img/proyectos/8-modelado_est_stanley_condominium/portada.jpg",
    enlace: "#",
    etiquetas: [
      "Revit",
      "BIM",
      "Edificio",
      "Concreto Armado",
      "Diseño Estructural",
      "Modelado 3D",
    ],
    mencion: "estructural",
    fecha: "2021-12-05",
    logros: [
      "Modelado BIM estructural detallado del condominio",
      "Generación de documentación técnica para construcción",
      "Coordinación y revisión del modelo estructural",
    ],
    software_usado: "Revit",
    impacto:
      "Eficiencia en el diseño y mejora en la documentación técnica para la construcción.",
    galeria: [
      "./img/proyectos/8-modelado_est_stanley_condominium/imagen_1.jpg",
      "./img/proyectos/8-modelado_est_stanley_condominium/imagen_2.jpg",
      "./img/proyectos/8-modelado_est_stanley_condominium/imagen_3.jpg",
      "./img/proyectos/8-modelado_est_stanley_condominium/imagen_4.jpg",
    ],
  },
];
